---                                                                             
- name: Deploying properties files to {{ ENV }}_{{ instance }}                           
  hosts: "{{ nodes }}"                                                          
  vars_files:                                                                   
    - ../vars/paths-list
    - /home/ansiuser/.secrets
  environment:                                                                  
    ANSIBLE_CONFIG: "{{ ansiblecfg_path }}"                                     
  become: yes                                                                   
  become_user: root                                                             
  become_method: sudo                                                           
  roles:                                                                        
  - role: "{{ roles_path }}/{{ ENV }}-{{ app }}"                                            
... 
