---
# tasks file for prd-tomcat
- name: block for copying {{ configfile }} to {{ ENV }}_{{ instance }} server
  block:
  - name: backup of {{ configfile }}
    shell:
      cp -p /opt/cloudhost/liferay-tomcat/liferay_instance{{ num }}/{{ TomcatVersion }}/conf/context.xml  /opt/cloudhost/liferay-tomcat/configfiles-backup/{{ instance }}/context.xml-`date +%Y.%m.%d.%H.%M.%S`

  - name: copying {{ configfile }} file to {{ ENV }}_{{ instance }} target location
    copy:
      src: "{{ propertyfiles_src }}/{{ ENV }}/{{ app }}/tomcat{{ nodeNum }}/context.xml"
      dest: /opt/cloudhost/liferay-tomcat/liferay_instance{{ num }}/{{ TomcatVersion }}/conf/context.xml
      remote_src: no
      owner: liferay
      group: liferaygrp
      mode: 0755
  tags: context.xml

- name: block for copying {{ configfile }} to {{ ENV }}_{{ instance }} server
  block:
  - name: backup of {{ configfile }}
    shell:
      cp -p /opt/cloudhost/liferay-tomcat/liferay_instance{{ num }}/{{ TomcatVersion }}/conf/server.xml  /opt/cloudhost/liferay-tomcat/configfiles-backup/{{ instance }}/server.xml-`date +%Y.%m.%d.%H.%M.%S`

  - name: copying server.xml file to {{ ENV }}_{{ instance }} target location
    template:
      src: "{{ propertyfiles_src }}/{{ ENV }}/{{ app }}/tomcat{{ nodeNum }}/template/server.xml.j2"
      dest: /opt/cloudhost/liferay-tomcat/liferay_instance{{ num }}/{{ TomcatVersion }}/conf/server.xml
      remote_src: no
      owner: liferay
      group: liferaygrp
      mode: 0755
  tags: server.xml

- name: block for copying {{ configfile }} to {{ ENV }}_{{ instance }} server
  block:
  - name: backup of {{ configfile }}
    shell:
      cp -p /opt/cloudhost/liferay-tomcat/liferay_instance{{ num }}/{{ TomcatVersion }}/conf/tomcat-users.xml /opt/cloudhost/liferay-tomcat/configfiles-backup/{{ instance }}/tomcat-users.xml-`date +%Y.%m.%d.%H.%M.%S`

  - name: copying tomcat-users.xml file to {{ ENV }}_{{ instance }} target location
    copy:
      src: "{{ propertyfiles_src }}/{{ ENV }}/{{ app }}/tomcat{{ nodeNum }}/tomcat-users.xml"
      dest: /opt/cloudhost/liferay-tomcat/liferay_instance{{ num }}/{{ TomcatVersion }}/conf/tomcat-users.xml
      remote_src: no
      owner: liferay
      group: liferaygrp
      mode: 0755
  tags: tomcat-users.xml

- name: block for copying {{ configfile }} to {{ ENV }}_{{ instance }} server
  block:
  - name: backup of {{ configfile }}
    shell:
      cp -p /opt/cloudhost/liferay-tomcat/liferay_instance{{ num }}/{{ TomcatVersion }}/conf/web.xml /opt/cloudhost/liferay-tomcat/configfiles-backup/{{ instance }}/web.xml-`date +%Y.%m.%d.%H.%M.%S`

  - name: copying web.xml file to {{ ENV }}_{{ instance }} target location
    copy:
      src: "{{ propertyfiles_src }}/{{ ENV }}/{{ app }}/tomcat{{ nodeNum }}/web.xml"
      dest: /opt/cloudhost/liferay-tomcat/liferay_instance{{ num }}/{{ TomcatVersion }}/conf/web.xml
      remote_src: no
      owner: liferay
      group: liferaygrp
      mode: 0755
  tags: web.xml

- name: block for copying {{ configfile }} to {{ ENV }}_{{ instance }} server
  block:
  - name: backup of {{ configfile }}
    shell:
      cp -p /opt/cloudhost/liferay-tomcat/liferay_instance{{ num }}/{{ TomcatVersion }}/bin/setenv.sh /opt/cloudhost/liferay-tomcat/configfiles-backup/{{ instance }}/setenv.sh-`date +%Y.%m.%d.%H.%M.%S`

  - name: copying setenv.sh file to {{ ENV }}_{{ instance }} target location
    copy:
      src: "{{ propertyfiles_src }}/{{ ENV }}/{{ app }}/tomcat{{ nodeNum }}/setenv.sh"
      dest: /opt/cloudhost/liferay-tomcat/liferay_instance{{ num }}/{{ TomcatVersion }}/bin/setenv.sh
      remote_src: no
      owner: liferay
      group: liferaygrp
      mode: 0755
  tags: setenv.sh

- name: block for copying {{ configfile }} to {{ ENV }}_{{ instance }} server
  block:
  - name: backup of {{ configfile }}
    shell:
      cp -p /opt/cloudhost/liferay-tomcat/liferay_instance{{ num }}/{{ TomcatVersion }}/bin/shutdown.sh /opt/cloudhost/liferay-tomcat/configfiles-backup/{{ instance }}/shutdown.sh-`date +%Y.%m.%d.%H.%M.%S`

  - name: copying shutdown.sh file to {{ ENV }}_{{ instance }} target location
    copy:
      src: "{{ propertyfiles_src }}/{{ ENV }}/{{ app }}/tomcat{{ nodeNum }}/shutdown.sh"
      dest: /opt/cloudhost/liferay-tomcat/liferay_instance{{ num }}/{{ TomcatVersion }}/bin/shutdown.sh
      remote_src: no
      owner: liferay
      group: liferaygrp
      mode: 0755
  tags: shutdown.sh

- name: block for copying {{ configfile }} to {{ ENV }}_{{ instance }} server
  block:
  - name: backup of {{ configfile }}
    shell:
      cp -p /opt/cloudhost/liferay-tomcat/liferay_instance{{ num }}/{{ TomcatVersion }}/bin/startup.sh  /opt/cloudhost/liferay-tomcat/configfiles-backup/{{ instance }}/startup.sh-`date +%Y.%m.%d.%H.%M.%S`

  - name: copying startup.sh file to {{ ENV }}_{{ instance }} target location
    copy:
      src: "{{ propertyfiles_src }}/{{ ENV }}/{{ app }}/tomcat{{ nodeNum }}/startup.sh"
      dest: /opt/cloudhost/liferay-tomcat/liferay_instance{{ num }}/{{ TomcatVersion }}/bin/startup.sh
      remote_src: no
      owner: liferay
      group: liferaygrp
      mode: 0755
  tags: startup.sh
  
- name: block for restarting {{ instance }} services
  block:
  - name: Starting the {{ instance }} services
    command: su liferay -c  'sh /opt/cloudhost/liferay-tomcat/liferay_instance{{ num }}/{{ TomcatVersion }}/bin/startup.sh'
  tags:
    - "yes"
...
