---
# tasks file for liferay
- name: block for copying {{ configfile }} to {{ ENV }}_{{ instance }} server
  block:
  - name: backup of {{ configfile }}
    shell:
      cp -p /opt/cloudhost/liferay-tomcat/liferay_instance{{ num }}/portal-ext.properties  /opt/cloudhost/liferay-tomcat/configfiles-backup/{{ instance }}/portal-ext.properties-`date +%Y.%m.%d.%H.%M.%S`

  - name: copying {{ configfile }} file to {{ ENV }}_{{ instance }} target location
    copy:
      src: "{{ propertyfiles_src }}/{{ ENV }}/{{ app }}/{{ instance }}/portal-ext.properties"
      dest: /opt/cloudhost/liferay-tomcat/liferay_instance{{ num }}/portal-ext.properties
      remote_src: no
      owner: liferay
      group: liferaygrp
      mode: 0755
  tags: portal-ext.properties
  
- name: block for copying {{ configfile }} to {{ ENV }}_{{ instance }} server
  block:
  - name: backup of {{ configfile }}
    shell:
      cp -p /opt/cloudhost/liferay-tomcat/liferay_instance{{ num }}/osgi/configs/BundleBlacklistConfiguration  /opt/cloudhost/liferay-tomcat/configfiles-backup/{{ instance }}/BundleBlacklistConfiguration-`date +%Y.%m.%d.%H.%M.%S`

  - name: copying {{ configfile }} file to {{ ENV }}_{{ instance }} target location
    copy:
      src: "{{ propertyfiles_src }}/{{ ENV }}/{{ app }}/{{ instance }}/BundleBlacklistConfiguration"
      dest: /opt/cloudhost/liferay-tomcat/liferay_instance{{ num }}/osgi/configs/com.liferay.portal.bundle.blacklist.internal.BundleBlacklistConfiguration.config
      remote_src: no
      owner: liferay
      group: liferaygrp
      mode: 0755
  tags: BundleBlacklistConfiguration
  
- name: block for copying {{ configfile }} to {{ ENV }}_{{ instance }} server
  block:
  - name: backup of {{ configfile }}
    shell:
      cp -p /opt/cloudhost/liferay-tomcat/liferay_instance{{ num }}/osgi/configs/ElasticsearchConfiguration  /opt/cloudhost/liferay-tomcat/configfiles-backup/{{ instance }}/ElasticsearchConfiguration-`date +%Y.%m.%d.%H.%M.%S`

  - name: copying {{ configfile }} file to {{ ENV }}_{{ instance }} target location
    copy:
      src: "{{ propertyfiles_src }}/{{ ENV }}/{{ app }}/{{ instance }}/ElasticsearchConfiguration"
      dest: /opt/cloudhost/liferay-tomcat/liferay_instance{{ num }}/osgi/configs/com.liferay.portal.search.elasticsearch6.configuration.ElasticsearchConfiguration.config
      remote_src: no
      owner: liferay
      group: liferaygrp
      mode: 0755
  tags: ElasticsearchConfiguration 
  

  
- name: block for copying {{ configfile }} to {{ ENV }}_{{ instance }} server
  block:
  - name: backup of {{ configfile }}
    shell:
      cp -p /opt/cloudhost/liferay-tomcat/liferay_instance{{ num }}/osgi/configs/BasicAuthHeaderAuthVerifierConfiguration-default  /opt/cloudhost/liferay-tomcat/configfiles-backup/{{ instance }}/BasicAuthHeaderAuthVerifierConfiguration-default-`date +%Y.%m.%d.%H.%M.%S`

  - name: copying {{ configfile }} file to {{ ENV }}_{{ instance }} target location
    copy:
      src: "{{ propertyfiles_src }}/{{ ENV }}/{{ app }}/{{ instance }}/BasicAuthHeaderAuthVerifierConfiguration-default"
      dest: /opt/cloudhost/liferay-tomcat/liferay_instance{{ num }}/osgi/configs/com.liferay.portal.security.auth.verifier.basic.auth.header.module.configuration.BasicAuthHeaderAuthVerifierConfiguration-default.cfg
      remote_src: no
      owner: liferay
      group: liferaygrp
      mode: 0755
  tags: BasicAuthHeaderAuthVerifierConfiguration-default
  
- name: block for copying {{ configfile }} to {{ ENV }}_{{ instance }} server
  block:
  - name: backup of {{ configfile }}
    shell:
      cp -p /opt/cloudhost/liferay-tomcat/liferay_instance{{ num }}/osgi/configs/PortalSessionAuthVerifierConfiguration-default  /opt/cloudhost/liferay-tomcat/configfiles-backup/{{ instance }}/PortalSessionAuthVerifierConfiguration-default-`date +%Y.%m.%d.%H.%M.%S`

  - name: copying {{ configfile }} file to {{ ENV }}_{{ instance }} target location
    copy:
      src: "{{ propertyfiles_src }}/{{ ENV }}/{{ app }}/{{ instance }}/PortalSessionAuthVerifierConfiguration-default"
      dest: /opt/cloudhost/liferay-tomcat/liferay_instance{{ num }}/osgi/configs/com.liferay.portal.security.auth.verifier.portal.session.module.configuration.PortalSessionAuthVerifierConfiguration-default.cfg
      remote_src: no
      owner: liferay
      group: liferaygrp
      mode: 0755
  tags: PortalSessionAuthVerifierConfiguration-default
  

- name: block for copying {{ configfile }} to {{ ENV }}_{{ instance }} server
  block:
  - name: backup of {{ configfile }}
    shell:
      cp -p /opt/cloudhost/liferay-tomcat/liferay_instance{{ num }}/osgi/configs/TunnelAuthVerifierConfiguration-default  /opt/cloudhost/liferay-tomcat/configfiles-backup/{{ instance }}/TunnelAuthVerifierConfiguration-default-`date +%Y.%m.%d.%H.%M.%S`

  - name: copying {{ configfile }} file to {{ ENV }}_{{ instance }} target location
    copy:
      src: "{{ propertyfiles_src }}/{{ ENV }}/{{ app }}/{{ instance }}/TunnelAuthVerifierConfiguration-default"
      dest: /opt/cloudhost/liferay-tomcat/liferay_instance{{ num }}/osgi/configs/com.liferay.portal.security.auth.verifier.tunnel.module.configuration.TunnelAuthVerifierConfiguration-default.cfg
      remote_src: no
      owner: liferay
      group: liferaygrp
      mode: 0755
  tags: TunnelAuthVerifierConfiguration-default
  
- name: block for copying {{ configfile }} to {{ ENV }}_{{ instance }} server
  block:
  - name: backup of {{ configfile }}
    shell:
      cp -p /opt/cloudhost/liferay-tomcat/liferay_instance{{ num }}/osgi/configs/FileSystemStoreConfiguration  /opt/cloudhost/liferay-tomcat/configfiles-backup/{{ instance }}/FileSystemStoreConfiguration-`date +%Y.%m.%d.%H.%M.%S`

  - name: copying {{ configfile }} file to {{ ENV }}_{{ instance }} target location
    copy:
      src: "{{ propertyfiles_src }}/{{ ENV }}/{{ app }}/{{ instance }}/FileSystemStoreConfiguration"
      dest: /opt/cloudhost/liferay-tomcat/liferay_instance{{ num }}/osgi/configs/com.liferay.portal.store.file.system.configuration.FileSystemStoreConfiguration.config
      remote_src: no
      owner: liferay
      group: liferaygrp
      mode: 0755
  tags: FileSystemStoreConfiguration
  

- name: block for copying {{ configfile }} to {{ ENV }}_{{ instance }} server
  block:
  - name: backup of {{ configfile }}
    shell:
      cp -p /opt/cloudhost/liferay-tomcat/liferay_instance{{ num }}/osgi/configs/solr  /opt/cloudhost/liferay-tomcat/configfiles-backup/{{ instance }}/ComponentBlacklistConfiguration-`date +%Y.%m.%d.%H.%M.%S`

  - name: copying {{ configfile }} file to {{ ENV }}_{{ instance }} target location
    copy:
      src: "{{ propertyfiles_src }}/{{ ENV }}/{{ app }}/{{ instance }}/ComponentBlacklistConfiguration"
      dest: /opt/cloudhost/liferay-tomcat/liferay_instance{{ num }}/osgi/configs/com.liferay.portal.component.blacklist.internal.ComponentBlacklistConfiguration.config
      remote_src: no
      owner: liferay
      group: liferaygrp
      mode: 0755
  tags: ComponentBlacklistConfiguration
  
  
- name: block for copying {{ configfile }} to {{ ENV }}_{{ instance }} server
  block:
  - name: backup of {{ configfile }}
    shell:
      cp -p /opt/cloudhost/liferay-tomcat/liferay_instance{{ num }}/supplier-ready-portal-application.properties /opt/cloudhost/liferay-tomcat/configfiles-backup/{{ instance }}/supplier-ready-portal-application.properties-`date +%Y.%m.%d.%H.%M.%S`

  - name: copying {{ configfile }} file to {{ ENV }}_{{ instance }} target location
    copy:
      src: "{{ propertyfiles_src }}/{{ ENV }}/{{ app }}/{{ instance }}/supplier-ready-portal-application.properties"
      dest: /opt/cloudhost/liferay-tomcat/liferay_instance{{ num }}/supplier-ready-portal-application.properties
      remote_src: no
      owner: liferay
      group: liferaygrp
      mode: 0755
  tags: supplier-ready-portal-application.properties
  
  
  
  
- name: block for copying {{ configfile }} to {{ ENV }}_{{ instance }} server
  block:
  - name: backup of {{ configfile }}
    shell:
      cp -p /opt/cloudhost/liferay-tomcat/liferay_instance{{ num }}/{{ TomcatVersion }}/webapps/ROOT/WEB-INF/classes/cluster-ehcache/liferay-multi-vm-clustered.xml  /opt/cloudhost/liferay-tomcat/configfiles-backup/{{ instance }}/liferay-multi-vm-clustered.xml-`date +%Y.%m.%d.%H.%M.%S`

  - name: copying liferay-multi-vm-clustered.xml file to {{ ENV }}_{{ instance }} target location
    copy:
      src: "{{ propertyfiles_src }}/{{ ENV }}/{{ app }}/{{ instance }}/liferay-multi-vm-clustered.xml"
      dest: /opt/cloudhost/liferay-tomcat/liferay_instance{{ num }}/{{ TomcatVersion }}/webapps/ROOT/WEB-INF/classes/cluster-ehcache/liferay-multi-vm-clustered.xml
      remote_src: no
      owner: liferay
      group: liferaygrp
      mode: 0755
  tags: liferay-multi-vm-clustered.xml
  
  
- name: block for copying {{ configfile }} to {{ ENV }}_{{ instance }} server
  block:
  - name: backup of {{ configfile }}
    shell:
      cp -p /opt/cloudhost/liferay-tomcat/liferay_instance{{ num }}/{{ TomcatVersion }}/webapps/ROOT/WEB-INF/classes/cluster-ehcache/liferay-single-vm.xml  /opt/cloudhost/liferay-tomcat/configfiles-backup/{{ instance }}/liferay-single-vm.xml-`date +%Y.%m.%d.%H.%M.%S`

  - name: copying liferay-single-vm.xml file to {{ ENV }}_{{ instance }} target location
    copy:
      src: "{{ propertyfiles_src }}/{{ ENV }}/{{ app }}/{{ instance }}/liferay-single-vm.xml"
      dest: /opt/cloudhost/liferay-tomcat/liferay_instance{{ num }}/{{ TomcatVersion }}/webapps/ROOT/WEB-INF/classes/cluster-ehcache/liferay-single-vm.xml
      remote_src: no
      owner: liferay
      group: liferaygrp
      mode: 0755
  tags: liferay-single-vm.xml
  
  
  
- name: block for copying {{ configfile }} to {{ ENV }}_{{ instance }} server
  block:
  - name: backup of {{ configfile }}
    shell:
      cp -p /opt/cloudhost/liferay-tomcat/liferay_instance{{ num }}/{{ TomcatVersion }}/webapps/ROOT/WEB-INF/classes/META-INF/portal-log4j-ext.xml /opt/cloudhost/liferay-tomcat/configfiles-backup/{{ instance }}/portal-log4j-ext.xml-`date +%Y.%m.%d.%H.%M.%S`

  - name: copying web.xml file to {{ ENV }}_{{ instance }} target location
    copy:
      src: "{{ propertyfiles_src }}/{{ ENV }}/{{ app }}/{{ instance }}/portal-log4j-ext.xml"
      dest: /opt/cloudhost/liferay-tomcat/liferay_instance{{ num }}/{{ TomcatVersion }}/webapps/ROOT/WEB-INF/classes/META-INF/portal-log4j-ext.xml
      remote_src: no
      owner: liferay
      group: liferaygrp
      mode: 0755
  tags: portal-log4j-ext.xml
  
  
- name: block for restarting {{ instance }} services
  block:
  - name: Starting the {{ instance }} services
    command: sh /opt/cloudhost/liferay-tomcat/liferay_instance{{ num }}/{{ TomcatVersion }}/bin/liferay_restart.sh
  tags:
    - "yes"
