---
# tasks file for elasticsearch
- name: block for copying {{ configfile }} to {{ ENV }}_{{ instance }} server
  block:
  - name: backup of {{ configfile }}
    shell:
      cp -p /etc/elasticsearch/elasticsearch.yml  /etc/elasticsearch/elasticsearch-backup/elasticsearch.yml-`date +%Y.%m.%d.%H.%M.%S`
  - name: copying {{ configfile }} file to {{ ENV }}_{{ instance }} target location
    copy:
      src: "{{ propertyfiles_src }}/{{ ENV }}/{{ app }}/{{ instance }}/elasticsearch.yml"
      dest: /etc/elasticsearch/elasticsearch.yml
      remote_src: no
      owner: elasticsearch
      group: elasticsearch
      mode: 0755
  tags: elasticsearch.yml
     
- name: block for restarting the elasticsearch services
  block:
  - name: Restarting the elasticsearch services
    service:
      name: elasticsearch
      state: restarted
  tags: 
    - "yes"
...
